In [3]:
# Importing pandas
import pandas as pd

In [4]:
# Loading 2025 monthly data into separate DataFrames to be merged later
df_1 = pd.read_csv('202501-divvy-tripdata.csv')
df_2 = pd.read_csv('202502-divvy-tripdata.csv')
df_3 = pd.read_csv('202503-divvy-tripdata.csv')
df_4 = pd.read_csv('202504-divvy-tripdata.csv')
df_5 = pd.read_csv('202505-divvy-tripdata.csv')
df_6 = pd.read_csv('202506-divvy-tripdata.csv')
df_7 = pd.read_csv('202507-divvy-tripdata.csv')
df_8 = pd.read_csv('202508-divvy-tripdata.csv')
df_9 = pd.read_csv('202509-divvy-tripdata.csv')
df_10 = pd.read_csv('202510-divvy-tripdata.csv')
df_11 = pd.read_csv('202511-divvy-tripdata.csv')
df_12 = pd.read_csv('202512-divvy-tripdata.csv')
# Loading 2024 monthly data into separate DataFrames to be merged later
df_13 = pd.read_csv('202401-divvy-tripdata.csv')
df_14 = pd.read_csv('202402-divvy-tripdata.csv')
df_15 = pd.read_csv('202403-divvy-tripdata.csv')
df_16 = pd.read_csv('202404-divvy-tripdata.csv')
df_17 = pd.read_csv('202405-divvy-tripdata.csv')
df_18 = pd.read_csv('202406-divvy-tripdata.csv')
df_19 = pd.read_csv('202407-divvy-tripdata.csv')
df_20 = pd.read_csv('202408-divvy-tripdata.csv')
df_21 = pd.read_csv('202409-divvy-tripdata.csv')
df_22 = pd.read_csv('202410-divvy-tripdata.csv')
df_23 = pd.read_csv('202411-divvy-tripdata.csv')
df_24 = pd.read_csv('202412-divvy-tripdata.csv')

In [5]:
# Checking the dataframes for consistency before merging
df_1.info()
df_2.info()
df_3.info()
df_4.info()
df_5.info()
df_6.info()
df_7.info()
df_8.info()
df_9.info()
df_10.info()
df_11.info()
df_12.info()
df_13.info()
df_14.info()
df_15.info()
df_16.info()
df_17.info()
df_18.info()
df_19.info()
df_20.info()
df_21.info()
df_22.info()
df_23.info()
df_24.info()

<class 'pandas.DataFrame'>
RangeIndex: 138689 entries, 0 to 138688
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             138689 non-null  str
 1   rideable_type       138689 non-null  str
 2   started_at          138689 non-null  str
 3   ended_at            138689 non-null  str
 4   start_station_name  115837 non-null  str
 5   start_station_id    115837 non-null  str
 6   end_station_name    114616 non-null  str
 7   end_station_id      114616 non-null  str
 8   start_lat           138689 non-null  float64
 9   start_lng           138689 non-null  float64
 10  end_lat             138628 non-null  float64
 11  end_lng             138628 non-null  float64
 12  member_casual       138689 non-null  str
dtypes: float64(4), str(9)
memory usage: 13.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 151880 entries, 0 to 151879
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             151880 non-null  str
 1   rideable_type       151880 non-null  str
 2   started_at          151880 non-null  str
 3   ended_at            151880 non-null  str
 4   start_station_name  125952 non-null  str
 5   start_station_id    125952 non-null  str
 6   end_station_name    124631 non-null  str
 7   end_station_id      124631 non-null  str
 8   start_lat           151880 non-null  float64
 9   start_lng           151880 non-null  float64
 10  end_lat             151823 non-null  float64
 11  end_lng             151823 non-null  float64
 12  member_casual       151880 non-null  str
dtypes: float64(4), str(9)
memory usage: 15.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 298155 entries, 0 to 298154
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             298155 non-null  str
 1   rideable_type       298155 non-null  str
 2   started_at          298155 non-null  str
 3   ended_at            298155 non-null  str
 4   start_station_name  242818 non-null  str
 5   start_station_id    242818 non-null  str
 6   end_station_name    240171 non-null  str
 7   end_station_id      240171 non-null  str
 8   start_lat           298155 non-null  float64
 9   start_lng           298155 non-null  float64
 10  end_lat             297914 non-null  float64
 11  end_lng             297914 non-null  float64
 12  member_casual       298155 non-null  str
dtypes: float64(4), str(9)
memory usage: 29.6 MB
<class 'pandas.DataFrame'>
RangeIndex: 371341 entries, 0 to 371340
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             371341 non-null  str
 1   rideable_type       371341 non-null  str
 2   started_at          371341 non-null  str
 3   ended_at            371341 non-null  str
 4   start_station_name  300145 non-null  str
 5   start_station_id    300145 non-null  str
 6   end_station_name    297706 non-null  str
 7   end_station_id      297706 non-null  str
 8   start_lat           371341 non-null  float64
 9   start_lng           371341 non-null  float64
 10  end_lat             371052 non-null  float64
 11  end_lng             371052 non-null  float64
 12  member_casual       371341 non-null  str
dtypes: float64(4), str(9)
memory usage: 36.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 502456 entries, 0 to 502455
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             502456 non-null  str
 1   rideable_type       502456 non-null  str
 2   started_at          502456 non-null  str
 3   ended_at            502456 non-null  str
 4   start_station_name  399096 non-null  str
 5   start_station_id    399096 non-null  str
 6   end_station_name    395020 non-null  str
 7   end_station_id      395020 non-null  str
 8   start_lat           502456 non-null  float64
 9   start_lng           502456 non-null  float64
 10  end_lat             501905 non-null  float64
 11  end_lng             501905 non-null  float64
 12  member_casual       502456 non-null  str
dtypes: float64(4), str(9)
memory usage: 49.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 678904 entries, 0 to 678903
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             678904 non-null  str
 1   rideable_type       678904 non-null  str
 2   started_at          678904 non-null  str
 3   ended_at            678904 non-null  str
 4   start_station_name  528000 non-null  str
 5   start_station_id    528000 non-null  str
 6   end_station_name    522132 non-null  str
 7   end_station_id      522132 non-null  str
 8   start_lat           678904 non-null  float64
 9   start_lng           678904 non-null  float64
 10  end_lat             677916 non-null  float64
 11  end_lng             677916 non-null  float64
 12  member_casual       678904 non-null  str
dtypes: float64(4), str(9)
memory usage: 67.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 763432 entries, 0 to 763431
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             763432 non-null  str
 1   rideable_type       763432 non-null  str
 2   started_at          763432 non-null  str
 3   ended_at            763432 non-null  str
 4   start_station_name  589903 non-null  str
 5   start_station_id    589903 non-null  str
 6   end_station_name    581926 non-null  str
 7   end_station_id      581926 non-null  str
 8   start_lat           763432 non-null  float64
 9   start_lng           763432 non-null  float64
 10  end_lat             762461 non-null  float64
 11  end_lng             762461 non-null  float64
 12  member_casual       763432 non-null  str
dtypes: float64(4), str(9)
memory usage: 75.7 MB
<class 'pandas.DataFrame'>
RangeIndex: 790177 entries, 0 to 790176
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             790177 non-null  str
 1   rideable_type       790177 non-null  str
 2   started_at          790177 non-null  str
 3   ended_at            790177 non-null  str
 4   start_station_name  613056 non-null  str
 5   start_station_id    613056 non-null  str
 6   end_station_name    605417 non-null  str
 7   end_station_id      605417 non-null  str
 8   start_lat           790177 non-null  float64
 9   start_lng           790177 non-null  float64
 10  end_lat             789484 non-null  float64
 11  end_lng             789484 non-null  float64
 12  member_casual       790177 non-null  str
dtypes: float64(4), str(9)
memory usage: 78.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 714759 entries, 0 to 714758
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             714759 non-null  str
 1   rideable_type       714759 non-null  str
 2   started_at          714759 non-null  str
 3   ended_at            714759 non-null  str
 4   start_station_name  558498 non-null  str
 5   start_station_id    558498 non-null  str
 6   end_station_name    550276 non-null  str
 7   end_station_id      550276 non-null  str
 8   start_lat           714759 non-null  float64
 9   start_lng           714759 non-null  float64
 10  end_lat             714140 non-null  float64
 11  end_lng             714140 non-null  float64
 12  member_casual       714759 non-null  str
dtypes: float64(4), str(9)
memory usage: 70.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 646039 entries, 0 to 646038
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             646039 non-null  str
 1   rideable_type       646039 non-null  str
 2   started_at          646039 non-null  str
 3   ended_at            646039 non-null  str
 4   start_station_name  501060 non-null  str
 5   start_station_id    501060 non-null  str
 6   end_station_name    492573 non-null  str
 7   end_station_id      492573 non-null  str
 8   start_lat           646039 non-null  float64
 9   start_lng           646039 non-null  float64
 10  end_lat             645453 non-null  float64
 11  end_lng             645453 non-null  float64
 12  member_casual       646039 non-null  str
dtypes: float64(4), str(9)
memory usage: 64.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 356628 entries, 0 to 356627
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             356628 non-null  str
 1   rideable_type       356628 non-null  str
 2   started_at          356628 non-null  str
 3   ended_at            356628 non-null  str
 4   start_station_name  280348 non-null  str
 5   start_station_id    280348 non-null  str
 6   end_station_name    274732 non-null  str
 7   end_station_id      274732 non-null  str
 8   start_lat           356628 non-null  float64
 9   start_lng           356628 non-null  float64
 10  end_lat             356271 non-null  float64
 11  end_lng             356271 non-null  float64
 12  member_casual       356628 non-null  str
dtypes: float64(4), str(9)
memory usage: 35.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 140534 entries, 0 to 140533
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             140534 non-null  str
 1   rideable_type       140534 non-null  str
 2   started_at          140534 non-null  str
 3   ended_at            140534 non-null  str
 4   start_station_name  113608 non-null  str
 5   start_station_id    113608 non-null  str
 6   end_station_name    110489 non-null  str
 7   end_station_id      110489 non-null  str
 8   start_lat           140534 non-null  float64
 9   start_lng           140534 non-null  float64
 10  end_lat             140412 non-null  float64
 11  end_lng             140412 non-null  float64
 12  member_casual       140534 non-null  str
dtypes: float64(4), str(9)
memory usage: 13.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 144873 entries, 0 to 144872
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             144873 non-null  str
 1   rideable_type       144873 non-null  str
 2   started_at          144873 non-null  str
 3   ended_at            144873 non-null  str
 4   start_station_name  125708 non-null  str
 5   start_station_id    125708 non-null  str
 6   end_station_name    124124 non-null  str
 7   end_station_id      124124 non-null  str
 8   start_lat           144873 non-null  float64
 9   start_lng           144873 non-null  float64
 10  end_lat             144585 non-null  float64
 11  end_lng             144585 non-null  float64
 12  member_casual       144873 non-null  str
dtypes: float64(4), str(9)
memory usage: 14.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 223164 entries, 0 to 223163
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             223164 non-null  str
 1   rideable_type       223164 non-null  str
 2   started_at          223164 non-null  str
 3   ended_at            223164 non-null  str
 4   start_station_name  199746 non-null  str
 5   start_station_id    199746 non-null  str
 6   end_station_name    198013 non-null  str
 7   end_station_id      198013 non-null  str
 8   start_lat           223164 non-null  float64
 9   start_lng           223164 non-null  float64
 10  end_lat             222846 non-null  float64
 11  end_lng             222846 non-null  float64
 12  member_casual       223164 non-null  str
dtypes: float64(4), str(9)
memory usage: 22.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 301687 entries, 0 to 301686
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             301687 non-null  str
 1   rideable_type       301687 non-null  str
 2   started_at          301687 non-null  str
 3   ended_at            301687 non-null  str
 4   start_station_name  257432 non-null  str
 5   start_station_id    257432 non-null  str
 6   end_station_name    254547 non-null  str
 7   end_station_id      254547 non-null  str
 8   start_lat           301687 non-null  float64
 9   start_lng           301687 non-null  float64
 10  end_lat             301291 non-null  float64
 11  end_lng             301291 non-null  float64
 12  member_casual       301687 non-null  str
dtypes: float64(4), str(9)
memory usage: 29.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 415025 entries, 0 to 415024
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             415025 non-null  str
 1   rideable_type       415025 non-null  str
 2   started_at          415025 non-null  str
 3   ended_at            415025 non-null  str
 4   start_station_name  340232 non-null  str
 5   start_station_id    340232 non-null  str
 6   end_station_name    336506 non-null  str
 7   end_station_id      336506 non-null  str
 8   start_lat           415025 non-null  float64
 9   start_lng           415025 non-null  float64
 10  end_lat             414546 non-null  float64
 11  end_lng             414546 non-null  float64
 12  member_casual       415025 non-null  str
dtypes: float64(4), str(9)
memory usage: 41.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 609493 entries, 0 to 609492
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             609493 non-null  str
 1   rideable_type       609493 non-null  str
 2   started_at          609493 non-null  str
 3   ended_at            609493 non-null  str
 4   start_station_name  500445 non-null  str
 5   start_station_id    500445 non-null  str
 6   end_station_name    496762 non-null  str
 7   end_station_id      496762 non-null  str
 8   start_lat           609493 non-null  float64
 9   start_lng           609493 non-null  float64
 10  end_lat             608709 non-null  float64
 11  end_lng             608709 non-null  float64
 12  member_casual       609493 non-null  str
dtypes: float64(4), str(9)
memory usage: 60.5 MB
<class 'pandas.DataFrame'>
RangeIndex: 710721 entries, 0 to 710720
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             710721 non-null  str
 1   rideable_type       710721 non-null  str
 2   started_at          710721 non-null  str
 3   ended_at            710721 non-null  str
 4   start_station_name  566696 non-null  str
 5   start_station_id    566696 non-null  str
 6   end_station_name    562694 non-null  str
 7   end_station_id      562694 non-null  str
 8   start_lat           710721 non-null  float64
 9   start_lng           710721 non-null  float64
 10  end_lat             709597 non-null  float64
 11  end_lng             709597 non-null  float64
 12  member_casual       710721 non-null  str
dtypes: float64(4), str(9)
memory usage: 70.5 MB
<class 'pandas.DataFrame'>
RangeIndex: 748962 entries, 0 to 748961
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             748962 non-null  str
 1   rideable_type       748962 non-null  str
 2   started_at          748962 non-null  str
 3   ended_at            748962 non-null  str
 4   start_station_name  611997 non-null  str
 5   start_station_id    611997 non-null  str
 6   end_station_name    609738 non-null  str
 7   end_station_id      609738 non-null  str
 8   start_lat           748962 non-null  float64
 9   start_lng           748962 non-null  float64
 10  end_lat             747871 non-null  float64
 11  end_lng             747871 non-null  float64
 12  member_casual       748962 non-null  str
dtypes: float64(4), str(9)
memory usage: 74.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 755639 entries, 0 to 755638
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             755639 non-null  str
 1   rideable_type       755639 non-null  str
 2   started_at          755639 non-null  str
 3   ended_at            755639 non-null  str
 4   start_station_name  615048 non-null  str
 5   start_station_id    615048 non-null  str
 6   end_station_name    613414 non-null  str
 7   end_station_id      613414 non-null  str
 8   start_lat           755639 non-null  float64
 9   start_lng           755639 non-null  float64
 10  end_lat             754612 non-null  float64
 11  end_lng             754612 non-null  float64
 12  member_casual       755639 non-null  str
dtypes: float64(4), str(9)
memory usage: 74.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 821276 entries, 0 to 821275
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             821276 non-null  str
 1   rideable_type       821276 non-null  str
 2   started_at          821276 non-null  str
 3   ended_at            821276 non-null  str
 4   start_station_name  632126 non-null  str
 5   start_station_id    632126 non-null  str
 6   end_station_name    628326 non-null  str
 7   end_station_id      628326 non-null  str
 8   start_lat           821276 non-null  float64
 9   start_lng           821276 non-null  float64
 10  end_lat             820523 non-null  float64
 11  end_lng             820523 non-null  float64
 12  member_casual       821276 non-null  str
dtypes: float64(4), str(9)
memory usage: 81.5 MB
<class 'pandas.DataFrame'>
RangeIndex: 616281 entries, 0 to 616280
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             616281 non-null  str
 1   rideable_type       616281 non-null  str
 2   started_at          616281 non-null  str
 3   ended_at            616281 non-null  str
 4   start_station_name  509134 non-null  str
 5   start_station_id    509134 non-null  str
 6   end_station_name    506764 non-null  str
 7   end_station_id      506764 non-null  str
 8   start_lat           616281 non-null  float64
 9   start_lng           616281 non-null  float64
 10  end_lat             615713 non-null  float64
 11  end_lng             615713 non-null  float64
 12  member_casual       616281 non-null  str
dtypes: float64(4), str(9)
memory usage: 61.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 335075 entries, 0 to 335074
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             335075 non-null  str
 1   rideable_type       335075 non-null  str
 2   started_at          335075 non-null  str
 3   ended_at            335075 non-null  str
 4   start_station_name  278872 non-null  str
 5   start_station_id    278872 non-null  str
 6   end_station_name    277431 non-null  str
 7   end_station_id      277431 non-null  str
 8   start_lat           335075 non-null  float64
 9   start_lng           335075 non-null  float64
 10  end_lat             334802 non-null  float64
 11  end_lng             334802 non-null  float64
 12  member_casual       335075 non-null  str
dtypes: float64(4), str(9)
memory usage: 33.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 178372 entries, 0 to 178371
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             178372 non-null  str

In [6]:
# Combine all monthly DataFrames into one for the entire 2024-2025 period
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10, df_11, df_12, df_13, df_14, df_15, df_16, df_17, df_18, df_19, df_20, df_21, df_22, df_23, df_24], ignore_index=True)

In [7]:
# Checking the combined DataFrame after merging
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [8]:
# Checking for null values in the combined DataFrame
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    2258624
start_station_id      2258624
end_station_name      2347958
end_station_id        2347958
start_lat                   0
start_lng                   0
end_lat                 12767
end_lng                 12767
member_casual               0
dtype: int64

In [9]:
# Found null values, but lattitude and longitude end values are not equal to start station and end station values
# Dropping null values in end_latitude and end_longitude columns
df.dropna(subset=['end_lat', 'end_lng'], inplace=True)

In [10]:
# Checking for null values in the combined DataFrame after dropping
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    2258624
start_station_id      2258624
end_station_name      2335191
end_station_id        2335191
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
member_casual               0
dtype: int64

In [11]:
# End station nulls not equal to start station for some entries - dropping all null values for simplicity
df.dropna(inplace=True)

In [12]:
# Checking for null values in the combined DataFrame after dropping
df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [13]:
# All null values have been addressed
# Checking for duplicate entries in the combined DataFrame
df.duplicated().sum()

np.int64(0)

In [14]:
# No duplicate entries found
# Checking the values after cleaning
df['member_casual'].value_counts()

member_casual
member    5056677
casual    2844886
Name: count, dtype: int64

In [15]:
# Checking the values after cleaning
df['rideable_type'].value_counts()

rideable_type
classic_bike        4670555
electric_bike       3183181
electric_scooter      47827
Name: count, dtype: int64

In [16]:
# Checking values for consistency in start and end time columns to measure ride duration
df['started_at'].head()
df['ended_at'].head()

0    2025-01-21 17:37:52.015
1    2025-01-11 15:49:11.139
2    2025-01-02 15:28:03.230
3    2025-01-23 08:52:40.047
4    2025-01-16 08:41:06.767
Name: ended_at, dtype: str

In [17]:
# Creating a new column for ride duration by finding the difference between end time and start time
df['ride_duration'] = pd.to_datetime(df['ended_at']) - pd.to_datetime(df['started_at'])

ValueError: time data "2024-01-12 15:37:59" doesn't match format "%Y-%m-%d %H:%M:%S.%f". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [18]:
# Found inconsistant date time stamps, finding the number of invalid date time stamps in start and end time columns
started_temp = pd.to_datetime(df['started_at'], errors='coerce')
invalid_started = started_temp.isna().sum()
print(f"Invalid 'started_at' count: {invalid_started}")

Invalid 'started_at' count: 1268788

In [19]:
# Found inconsistant date time stamps,, finding the number of invalid date time stamps in start and end time columns
ended_temp = pd.to_datetime(df['ended_at'], errors='coerce')
invalid_ended = ended_temp.isna().sum()
print(f"Invalid 'ended_at' count: {invalid_ended}")

Invalid 'ended_at' count: 1268788

In [20]:
# The count on both start and end time columns are the same, so we can reformat the invalid date time stamps to NaT
# and recalculate the ride duration
df['ride_duration'] = pd.to_datetime(df['ended_at'], errors='coerce') - pd.to_datetime(df['started_at'], errors='coerce')

In [21]:
# Checking for null values in the combined DataFrame after reformatting date time stamps
df.isna().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name          0
start_station_id            0
end_station_name            0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
member_casual               0
ride_duration         1268788
dtype: int64

In [22]:
# Dropping null values from ride duration
df.dropna(inplace=True)

In [23]:
# Checking data after dropping null values from ride duration
df.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
ride_duration         0
dtype: int64

In [24]:
# Looking for out of the ordinary values in ride duration
df['ride_duration'].describe()

count                     6632775
mean       0 days 00:16:23.914344
std        0 days 00:34:33.079326
min      -1 days +23:04:34.458000
25%        0 days 00:05:51.148000
50%        0 days 00:10:06.937000
75%        0 days 00:18:01.566000
max        1 days 00:59:38.262000
Name: ride_duration, dtype: object

In [25]:
# finding how many rides have a duration of 10 seconds or less for false entries in the data or nonriders
zero_or_negative_duration = (df['ride_duration'] <= pd.Timedelta(seconds=10)).sum()
print(f"Number of rides with duration of 10 seconds or less: {zero_or_negative_duration}")

Number of rides with duration of 10 seconds or less: 12111

In [26]:
# finding how many rides have a duration of 24 hours or more for simplicity in the data and to drop outliers that will skew the data
long_duration = (df['ride_duration'] >= pd.Timedelta(24, unit='hours')).sum()
print(f"Number of rides with duration of 24 hours or more: {long_duration}")

Number of rides with duration of 24 hours or more: 201

In [27]:
# Dropping rides with duration of 10 seconds or less or more than 24 hours
df = df[(df['ride_duration'] > pd.Timedelta(seconds=10)) & (df['ride_duration'] < pd.Timedelta(24, unit='hours'))]

In [28]:
# Looking for out of the ordinary values in ride duration after dropping outliers
df['ride_duration'].describe()

count                   6620463
mean     0 days 00:16:23.074992
std      0 days 00:33:38.188420
min      0 days 00:00:10.001000
25%      0 days 00:05:52.374000
50%      0 days 00:10:08.042000
75%      0 days 00:18:02.887500
max      0 days 23:59:58.557000
Name: ride_duration, dtype: object

In [29]:
# Checking for null or bad syntax in started_at column
started_temp = pd.to_datetime(df['started_at'], errors='coerce')
invalid_started = started_temp.isna().sum()
print(f"Invalid 'started_at' count: {invalid_started}")

Invalid 'started_at' count: 0

In [ ]:
# Checking for null
df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
ride_duration         0
dtype: int64

In [32]:
# With data cleaned, I will now prepare three last columns for analysis: day of the week, month, and hour of the day. 
# I will extract this information from the start time column.
df['started_at'] = pd.to_datetime(df['started_at'])
df['start_day'] = df['started_at'].dt.day_name()
df['start_month'] = df['started_at'].dt.month_name()
df['start_hour'] = df['started_at'].dt.hour

In [33]:
# Final check of data after cleaning
df.info()

<class 'pandas.DataFrame'>
Index: 6620463 entries, 0 to 11413560
Data columns (total 17 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          datetime64[us]
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
 13  ride_duration       timedelta64[us]
 14  start_day           str
 15  start_month         str
 16  start_hour          int32
dtypes: datetime64[us](1), float64(4), int32(1), str(10), timedelta64[us](1)
memory usage: 883.9 MB

In [34]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration,start_day,start_month,start_hour
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,0 days 00:13:57.477000,Tuesday,January,17
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,0 days 00:05:04.344000,Saturday,January,15
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,0 days 00:11:35.500000,Thursday,January,15
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:03:34.233000,Thursday,January,8
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,0 days 00:02:34.429000,Thursday,January,8